# Generated by Django 5.0.6 on 2024-09-03 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_history_updated_date_productstock_updated_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_name', models.CharField(max_length=500, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='unit_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='product.units'),
        ),
    ]
