# Generated by Django 5.0.6 on 2024-09-04 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_units_product_unit_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='units',
            name='unit_id',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
    ]
