# Generated by Django 5.0.6 on 2024-09-04 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_units_unit_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unit_name',
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.units'),
        ),
    ]
