# Generated by Django 5.0.6 on 2024-09-04 05:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_remove_product_unit_name_product_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.units'),
        ),
        migrations.AddField(
            model_name='productstock',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.units'),
        ),
    ]
