# Generated by Django 5.0.6 on 2024-09-04 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_history_unit_productstock_unit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='productstock',
            name='unit',
        ),
        migrations.AddField(
            model_name='product',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
