# Generated by Django 5.0.6 on 2024-09-05 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_remove_history_unit_remove_productstock_unit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='units',
            name='unit_id',
        ),
        migrations.AlterField(
            model_name='product',
            name='unit',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.CASCADE, to='product.units'),
            preserve_default=False,
        ),
    ]
